ID_TO_ACTION = {
    0: 'Discard card in slot 0 from your hand',
    1: 'Discard card in slot 1 from your hand',
    2: 'Discard card in slot 2 from your hand',
    3: 'Discard card in slot 3 from your hand',
    4: 'Discard card in slot 4 from your hand',
    5: 'Play card in slot 0 from your hand',
    6: 'Play card in slot 1 from your hand',
    7: 'Play card in slot 2 from your hand',
    8: 'Play card in slot 3 from your hand',
    9: 'Play card in slot 4 from your hand',
    10: 'Hint red to teammate',
    11: 'Hint yellow to teammate',
    12: 'Hint green to teammate',
    13: 'Hint white to teammate',
    14: 'Hint blue to teammate',
    15: 'Hint rank 1 to teammate',
    16: 'Hint rank 2 to teammate',
    17: 'Hint rank 3 to teammate',
    18: 'Hint rank 4 to teammate',
    19: 'Hint rank 5 to teammate',
    20: 'No operation'
}

ACTION_TO_ID = {
    'discard card in slot 0 from your hand': 0,
    'discard card in slot 1 from your hand': 1,
    'discard card in slot 2 from your hand': 2,
    'discard card in slot 3 from your hand': 3,
    'discard card in slot 4 from your hand': 4,
    'play card in slot 0 from your hand': 5,
    'play card in slot 1 from your hand': 6,
    'play card in slot 2 from your hand': 7,
    'play card in slot 3 from your hand': 8,
    'play card in slot 4 from your hand': 9,
    'hint red to teammate': 10,
    'hint yellow to teammate': 11,
    'hint green to teammate': 12,
    'hint white to teammate': 13,
    'hint blue to teammate': 14,
    'hint rank 1 to teammate': 15,
    'hint rank 2 to teammate': 16,
    'hint rank 3 to teammate': 17,
    'hint rank 4 to teammate': 18,
    'hint rank 5 to teammate': 19,
    'no operation': 20
}

ID_TO_CARD = {
    0: "Red 1",
    1: "Red 2",
    2: "Red 3",
    3: "Red 4",
    4: "Red 5",
    5: "Yellow 1",
    6: "Yellow 2",
    7: "Yellow 3",
    8: "Yellow 4",
    9: "Yellow 5",
    10: "Green 1",
    11: "Green 2",
    12: "Green 3",
    13: "Green 4",
    14: "Green 5",
    15: "White 1",
    16: "White 2",
    17: "White 3",
    18: "White 4",
    19: "White 5",
    20: "Blue 1",
    21: "Blue 2",
    22: "Blue 3",
    23: "Blue 4",
    24: "Blue 5",
}

CARD_TO_CARD_ID = {
    "Red 1": 0,
    "Red 2": 1,
    "Red 3": 2,
    "Red 4": 3,
    "Red 5": 4,
    "Yellow 1": 5,
    "Yellow 2": 6,
    "Yellow 3": 7,
    "Yellow 4": 8,
    "Yellow 5": 9,
    "Green 1": 10,
    "Green 2": 11,
    "Green 3": 12,
    "Green 4": 13,
    "Green 5": 14,
    "White 1": 15,
    "White 2": 16,
    "White 3": 17,
    "White 4": 18,
    "White 5": 19,
    "Blue 1": 20,
    "Blue 2": 21,
    "Blue 3": 22,
    "Blue 4": 23,
    "Blue 5": 24,
}

ID_TO_COLOUR = {
    0: "Red",
    1: "Yellow",
    2: "Green",
    3: "White",
    4: "Blue",
}

ID_TO_RANK = {
    0: 1,
    1: 2,
    2: 3,
    3: 4,
    4: 5,
}

CARD_ID_TO_RANK = {
    0: 1,
    1: 2,
    2: 3,
    3: 4,
    4: 5,
    5: 1,
    6: 2,
    7: 3,
    8: 4,
    9: 5,
    10: 1,
    11: 2,
    12: 3,
    13: 4,
    14: 5,
    15: 1,
    16: 2,
    17: 3,
    18: 4,
    19: 5,
    20: 1,
    21: 2,
    22: 3,
    23: 4,
    24: 5,
}

FULL_COLOUR_NAMES = {
        "R": "Red",
        "Y": "Yellow",
        "G": "Green",
        "W": "White",
        "B": "Blue"
    }
